-- Parcours : synchronisation avec le CV PDF (5 postes).
-- À exécuter dans l'éditeur SQL Supabase du projet nlgfcrkmeslbkqqgatzq.

update public.translations
set data = jsonb_set(data, '{parcours,items}', '[{"y": "2016 — Aujourd''hui", "r": "Directrice de Production & Co-fondatrice", "c": "Super Motion", "d": "Pilotage de projets photo et vidéo de A à Z : conception, DA, devis, planning, repérage, casting, tournage, shooting, post-production, livraison. Campagnes 360, direction d''une équipe de 3 à 15 personnes, décisionnaire opérationnelle et budgétaire. BETC, Publicis, BBDO, TBWA, Romance, TAG Heuer, Vacheron Constantin, La Redoute, Asics, Krys Group, Avène, Kinder, Samsung, Fiat, Unesco."}, {"y": "2014 — 2016", "r": "Directrice des opérations & du trafic création", "c": "Geometry — WPP", "d": "Pilotage des opérations et coordination de projets digitaux et print, 15 créatifs internes et partenaires externes, contrôle budgétaire et reporting client. Piaget, Vogue, Croix Rouge, Coca-Cola, Nestlé, Alcatel."}, {"y": "2009 — 2014", "r": "Responsable achat d''art & production créative", "c": "Razorfish (ex Digitas)", "d": "Production vidéo de bout en bout, trafic création et production digitale pour 70 profils internes et freelances, achat d''art et négociation des droits. Hermès, Lancôme, Armani, Hennessy, Dassault, La Poste, Nissan, Renault."}, {"y": "2008 — 2009", "r": "Responsable trafic & achat d''art", "c": "Ailleurs Exactement", "d": "Coordination de productions, organisation de shootings et gestion des talents."}, {"y": "2007 — 2008", "r": "Responsable trafic création", "c": "TBWA", "d": "Pilotage du trafic création pour 40 créatifs internes : plannings, priorités et livraisons. Sourcing de prestataires, négociation des tarifs et gestion des droits."}]'::jsonb),
    updated_at = now()
where lang = 'fr';

update public.translations
set data = jsonb_set(data, '{parcours,items}', '[{"y": "2016 — Present", "r": "Production Director & Co-founder", "c": "Super Motion", "d": "End-to-end photo and video project management: concept, art direction, estimates, planning, location scouting, casting, filming, shooting, post-production, delivery. 360 campaigns, leading teams of 3 to 15, operational and budget decision-maker. BETC, Publicis, BBDO, TBWA, Romance, TAG Heuer, Vacheron Constantin, La Redoute, Asics, Krys Group, Avène, Kinder, Samsung, Fiat, Unesco."}, {"y": "2014 — 2016", "r": "Head of Operations & Creative Traffic", "c": "Geometry — WPP", "d": "Operations management and digital/print project coordination, 15 in-house creatives and external partners, budget control and client reporting. Piaget, Vogue, Croix Rouge, Coca-Cola, Nestlé, Alcatel."}, {"y": "2009 — 2014", "r": "Art Buying & Creative Production Manager", "c": "Razorfish (ex Digitas)", "d": "End-to-end video production, creative traffic and digital production across 70 in-house and freelance profiles, art buying and rights negotiation. Hermès, Lancôme, Armani, Hennessy, Dassault, La Poste, Nissan, Renault."}, {"y": "2008 — 2009", "r": "Traffic & Art Buying Manager", "c": "Ailleurs Exactement", "d": "Production coordination, shoot organisation and talent management."}, {"y": "2007 — 2008", "r": "Creative Traffic Manager", "c": "TBWA", "d": "Creative traffic for 40 in-house creatives: schedules, priorities and deliveries. Supplier sourcing, rate negotiation and rights management."}]'::jsonb),
    updated_at = now()
where lang = 'en';
