-- Projets : modèle défi / rôle / résultat et vidéos YouTube.
-- Les huit projets des textes validés par Sorya remplacent l'ancienne
-- sélection ; les vignettes viennent de la médiathèque (AVIF).

-- PMU sort de la selection : sa categorie « ai » disparait aussi,
-- il faut donc supprimer la ligne avant de resserrer la contrainte.
delete from public.projects where id = 'pmu';

-- Le filtre de la page Projets suit les nouveaux formats : le film
-- institutionnel et le clip entrent, la categorie IA sort.
alter table public.projects drop constraint if exists projects_category_check;
alter table public.projects add constraint projects_category_check
  check (category in ('brand', 'corp', 'doc', 'post', 'vfx', 'clip'));

alter table public.projects
  add column if not exists youtube text,
  add column if not exists challenge jsonb not null default '{"fr":"","en":""}'::jsonb,
  add column if not exists contribution jsonb not null default '{"fr":"","en":""}'::jsonb,
  add column if not exists outcome jsonb not null default '{"fr":"","en":""}'::jsonb;

insert into public.projects
  (id, sort_order, client, title, year, featured, pending, ai, vimeo, youtube, still, category,
   tag, role, descr, challenge, contribution, outcome, updated_at)
values
  ('kinder', 0, 'Kinder', 'La Magie de Noël', '2023', true, false, false, null, 'rYsz7y2RcwE', 'https://nlgfcrkmeslbkqqgatzq.supabase.co/storage/v1/object/public/media/lib/kinder-e1013d.avif', 'brand', '{"fr": "Campagne publicitaire : TV, digital et réseaux sociaux", "en": ""}'::jsonb, '{"fr": "Direction de production", "en": ""}'::jsonb, '{"fr": "Campagne de Noël déclinée en TV, digital et réseaux sociaux, tournée avec des enfants sur un planning de diffusion non négociable.", "en": ""}'::jsonb, '{"fr": "Kinder avait besoin de lancer sa campagne de Noël simultanément en TV, digital et réseaux sociaux, avec de nombreux livrables à produire sur un planning de diffusion non négociable et l''exigence que l''émotion reste sincère malgré l''ampleur du dispositif et la présence d''enfants sur le plateau.", "en": ""}'::jsonb, '{"fr": "J''ai défini et coordonné les équipes créatives, la production et la post-production sur l''ensemble des livrables, en construisant le plan de tournage autour du rythme des enfants plutôt que l''inverse et en restant sur le plateau à chaque étape, pour préserver la spontanéité de l''émotion sans jamais menacer la qualité des livrables.", "en": ""}'::jsonb, '{"fr": "Un ensemble de livrables cohérent sur tous les formats, prêt pour le lancement au moment stratégique des fêtes, sans compromis sur la qualité, l''authenticité de l''émotion ni sur le planning.", "en": ""}'::jsonb, now()),
  ('petitballon', 1, 'Le Petit Ballon', 'L''Accordeur de vin', '', true, false, false, null, 'xq5rWblQWBc', 'https://nlgfcrkmeslbkqqgatzq.supabase.co/storage/v1/object/public/media/lib/le-petit-ballon-8487a7.avif', 'brand', '{"fr": "Film de marque", "en": ""}'::jsonb, '{"fr": "Direction de production", "en": ""}'::jsonb, '{"fr": "Film de marque décalé sur un marché du vin très codifié, où l''humour du concept devait survivre aux arbitrages de production.", "en": ""}'::jsonb, '{"fr": "Le Petit Ballon voulait affirmer une identité de marque décalée sur un marché du vin très codifié, sans que les contraintes de production ne diluent l''humour et l''originalité du concept.", "en": ""}'::jsonb, '{"fr": "J''ai organisé et piloté les équipes créatives, la production et la post-production, en choisissant une équipe de tournage habituée aux formats décalés, du casting au repérage. Je suis restée présente sur le plateau pour que le ton du film soit respecté malgré les arbitrages de production et de budget.", "en": ""}'::jsonb, '{"fr": "Un film fidèle à l''identité décalée de la marque, livré sans compromis sur le ton ni sur le planning et le budget, renforçant sa singularité face aux codes plus classiques du secteur.", "en": ""}'::jsonb, now()),
  ('avene', 2, 'Avène', 'Comedomed', '2023', false, false, false, null, 'qFs1pP2rshg', 'https://nlgfcrkmeslbkqqgatzq.supabase.co/storage/v1/object/public/media/lib/avene-56021f.avif', 'post', '{"fr": "Post-production", "en": ""}'::jsonb, '{"fr": "Direction de post-production", "en": ""}'::jsonb, '{"fr": "Campagne internationale dermo-cosmétique : un rendu premium où le moindre écart de retouche engageait la confiance envers la marque.", "en": ""}'::jsonb, '{"fr": "Avène et Saatchi avaient besoin d''un rendu premium et crédible dermatologiquement pour une campagne internationale, avec un renfort d''experts en post-production. L''enjeu était de taille : le moindre écart de retouche pouvait nuire à la confiance envers la marque.", "en": ""}'::jsonb, '{"fr": "J''ai défini et coordonné une équipe d''experts en post-production (monteur, motion designer, 3D, retoucheur, comédiens voix off multilingues), en cadrant chaque étape et en m''intégrant au rythme et au budget du projet.", "en": ""}'::jsonb, '{"fr": "Un rendu naturel et premium, conforme aux standards dermo-cosmétiques sur l''ensemble des marchés de la campagne, livré dans le respect du planning et du budget.", "en": ""}'::jsonb, now()),
  ('krys', 3, 'Krys Group', 'L''art de bien voir', '2025', false, false, false, null, '-_Ri0Re0Ees', 'https://nlgfcrkmeslbkqqgatzq.supabase.co/storage/v1/object/public/media/lib/krys-63102b.avif', 'corp', '{"fr": "Film institutionnel", "en": ""}'::jsonb, '{"fr": "Direction de production", "en": ""}'::jsonb, '{"fr": "Film tourné dans le centre de production CODIR, au plus près de celles et ceux qui fabriquent les verres.", "en": ""}'::jsonb, '{"fr": "Réalisé à l''occasion de l''agrandissement du centre de production CODIR, le film avait pour enjeu de valoriser le savoir-faire et de mettre en lumière celles et ceux qui fabriquent, dans l''ombre du site, les verres qui améliorent la vision de millions de personnes.", "en": ""}'::jsonb, '{"fr": "J''ai piloté la production et la post-production, en concevant un plan de tournage discret calé sur les temps morts de la ligne de production du CODIR et en restant sur place pour laisser aux équipes le temps de s''habituer à la caméra avant le premier clap.", "en": ""}'::jsonb, '{"fr": "Un film institutionnel qui valorise la précision du savoir-faire et la fierté d''un groupe engagé, diffusé en interne, auprès des associés et du grand public.", "en": ""}'::jsonb, now()),
  ('asics', 4, 'ASICS × Ville de Paris', 'Paris, Bouge ton esprit', '2023', true, false, false, null, '0h6t_rdsIxM', 'https://nlgfcrkmeslbkqqgatzq.supabase.co/storage/v1/object/public/media/lib/asics-283852.avif', 'doc', '{"fr": "Documentaire", "en": ""}'::jsonb, '{"fr": "Coordination de production", "en": ""}'::jsonb, '{"fr": "Mini-documentaire sur le lien entre sport et santé mentale, tourné sur plusieurs mois d''interviews.", "en": ""}'::jsonb, '{"fr": "Produire pour Asics et la Ville de Paris un mini-documentaire sur le lien entre sport et santé mentale. Plusieurs mois de tournage et d''interviews pour capter des récits authentiques et lancer le programme Paris, Bouge ton esprit.", "en": ""}'::jsonb, '{"fr": "J''ai mis en place et suivi les équipes de production sur des phases clés du projet, en assurant un point de coordination de la pré-production au livrable.", "en": ""}'::jsonb, '{"fr": "Un film porté par des récits humains forts, qui a contribué à générer un fort engagement dès le lancement du programme.", "en": ""}'::jsonb, now()),
  ('tagheuer', 5, 'TAG Heuer', 'Iconic watches', '2020', false, false, false, null, 'lj0Cwl0w8FE', 'https://nlgfcrkmeslbkqqgatzq.supabase.co/storage/v1/object/public/media/lib/tag-heuer-cadf4c.avif', 'brand', '{"fr": "Contenus social media et salon", "en": ""}'::jsonb, '{"fr": "Direction de production", "en": ""}'::jsonb, '{"fr": "Modèles emblématiques filmés pour les réseaux sociaux et le salon Baselworld, à cadence resserrée.", "en": ""}'::jsonb, '{"fr": "TAG Heuer cherchait à présenter plusieurs modèles emblématiques sur les réseaux sociaux et lors du salon de l''horlogerie Baselworld, où la fenêtre d''attention est courte et chaque contenu doit servir l''image haut de gamme de la marque.", "en": ""}'::jsonb, '{"fr": "J''ai constitué les équipes de production et de post-production, en choisissant des experts de la haute horlogerie. J''ai été présente à chaque tournage pour tenir une cadence resserrée sans sacrifier le niveau de finition attendu d''une marque horlogère haut de gamme.", "en": ""}'::jsonb, '{"fr": "Une série de contenus livrée au rythme du plan média, renforçant la présence et l''image premium de la marque.", "en": ""}'::jsonb, now()),
  ('fiat', 6, 'Fiat', 'Abarth 500e', '2023', false, false, false, null, 'TW012v6R5gE', 'https://nlgfcrkmeslbkqqgatzq.supabase.co/storage/v1/object/public/media/lib/fiat-b12572.avif', 'vfx', '{"fr": "3D et post-production", "en": ""}'::jsonb, '{"fr": "Direction de production", "en": ""}'::jsonb, '{"fr": "Séquence 3D pour le lancement international, avec une transition invisible entre film de campagne et film produit.", "en": ""}'::jsonb, '{"fr": "Fiat visait une séquence 3D irréprochable pour le lancement international de l''Abarth 500e, avec une transition invisible entre film de campagne et film produit, sans marge sur le planning.", "en": ""}'::jsonb, '{"fr": "J''ai défini et coordonné une équipe de talents 3D en structurant chaque étape de validation, de l''animatique au rendu final, pour un rendu premium et naturel.", "en": ""}'::jsonb, '{"fr": "Une séquence 3D réaliste livrée dans les délais du lancement international, avec une transition fluide au service de la cohérence de la campagne.", "en": ""}'::jsonb, now()),
  ('universal', 7, 'Universal', 'Petit Jeu', '', false, false, false, null, 'SMyb3qNe3z0', 'https://nlgfcrkmeslbkqqgatzq.supabase.co/storage/v1/object/public/media/lib/petit-jeu-9619ba.avif', 'clip', '{"fr": "Clip", "en": ""}'::jsonb, '{"fr": "Direction de production", "en": ""}'::jsonb, '{"fr": "Clip d''Ours en featuring avec -M-, entre décor fait maison et motion design inspiré des jeux vidéo des années 90.", "en": ""}'::jsonb, '{"fr": "Universal voulait un clip qui illustre de manière singulière le titre Petit Jeu, interprété par Ours, en featuring avec -M-.", "en": ""}'::jsonb, '{"fr": "J''ai constitué les équipes de création et de production ainsi que le casting enfant, pour créer un clip unique mêlant tournage dans un décor fait maison et séquences en motion design rappelant les jeux vidéo des années 90.", "en": ""}'::jsonb, '{"fr": "Un clip fidèle à l''univers des deux artistes, chaleureux et plein de vie.", "en": ""}'::jsonb, now())
on conflict (id) do update set
  sort_order = excluded.sort_order, client = excluded.client, title = excluded.title,
  year = excluded.year, featured = excluded.featured, pending = excluded.pending, ai = excluded.ai,
  vimeo = excluded.vimeo, youtube = excluded.youtube, still = excluded.still, category = excluded.category,
  tag = excluded.tag, role = excluded.role, descr = excluded.descr,
  challenge = excluded.challenge, contribution = excluded.contribution, outcome = excluded.outcome,
  updated_at = now();

-- Filet : toute fiche hors selection sort egalement.
delete from public.projects where id not in ('kinder', 'petitballon', 'avene', 'krys', 'asics', 'tagheuer', 'fiat', 'universal');
